### ISSUE TITLE
Header may not contain more than a single header, new line detected at ....

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton-api-php#157]
In some join requests, users get stuck with the following error. What's going on? Could you help me?

```
Header may not contain more than a single header, new line detected at /var/www/xxxxx/vendor/symfony/http-foundation/Response.php:359)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/xxxxx/vendor/symfony/http-foundation/Response.php(359): header()
#2 /var/www/xxxxx/vendor/symfony/http-foundation/Response.php(393): Symfony\\Component\\HttpFoundation\\Response->sendHeaders()
#3 /var/www/xxxxx/public/index.php(62): Symfony\\Component\\HttpFoundation\\Response->send()
#4 {main}
"} 
```

**Comment by GhaziTriki** [comment]
@cod3r0k Do you still have the filed issue?

**Comment by aunglynn550** [comment]
i got exactly the same error still can't solve

**Comment by GhaziTriki** [comment]
It is technically possible to have duplicate headers in HTTP but up to the implementer to fix it.
