### ISSUE TITLE
String could not be parsed as XML

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton-api-php#96]
I followed the wiki and am trying this code: 

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

putenv("BBB_SERVER_BASE_URL=http://mydomain.tld/");
putenv("BBB_SECRET=123456789");

require("../vendor/autoload.php");


use BigBlueButton\BigBlueButton;
use BigBlueButton\Parameters\CreateMeetingParameters;

$bbb                 = new BigBlueButton();
$createMeetingParams = new CreateMeetingParameters('bbb-meeting-uid-65', 'BigBlueButton API Meeting');
$response            = $bbb->createMeeting($createMeetingParams);

echo "Created Meeting with ID: " . $response->getMeetingId();
```

But this gives me the following errors:
```
Warning: SimpleXMLElement::__construct(): Entity: line 6: parser error : Opening and ending tag mismatch: hr line 5 and body in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): </body> in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): ^ in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): Entity: line 7: parser error : Opening and ending tag mismatch: body line 3 and html in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): </html> in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): ^ in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Warning: SimpleXMLElement::__construct(): Entity: line 8: parser error : Premature end of data in tag html line 1 in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490

Fatal error: Uncaught Exception: String could not be parsed as XML in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:490 Stack trace: #0 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(490): SimpleXMLElement->__construct('<html>\r\n<head><...') #1 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(108): BigBlueButton\BigBlueButton->processXmlResponse('http://classevi...', '') #2 /var/www/bigbluebutton-default/test.php(17): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #3 {main} thrown in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 490
```

What's the problem ?

**Comment by toto4ds** [comment]
http**S**://mydomain.tld/bigbluebutton/ ?

**Comment by Entretoize** [comment]
It's ok I found that I didn't set the right server base url.

Ref: http://docs.bigbluebutton.org/2.2/install.html#4--install-bigbluebutton
